from src.application.abstractions.repositories.i_user_repository import IUserRepository
from src.application.abstractions.repositories.i_admin_user_repository import IAdminUserRepository
from src.application.abstractions.repositories.i_admin_session_repository import IAdminSessionRepository
from src.application.abstractions.repositories.i_legal_entity_repository import ILegalEntityRepository
from src.application.abstractions.repositories.i_organization_wallet_repository import IOrganizationWalletRepository
from src.application.abstractions.repositories.i_purchase_request_repository import IPurchaseRequestRepository
from src.application.abstractions.repositories.i_wallets_repository import IWalletRepository
from src.application.abstractions.repositories.i_order_repository import IOrderRepository
